import os
import sys
import pandas as pd
import numpy as np

def run_alpha_attribution(trades_df, mode="long", silent=False):
    """
    Takes the detail dataframe generated by vectorized_backtest.py
    and produces the Winner vs. Losers characteristics profile.
    """
    if trades_df is None or trades_df.empty:
        if not silent: print("No historical trades to attribute.")
        return None
        
    winners = trades_df[trades_df["Win"] == "YES"]
    losers = trades_df[trades_df["Win"] == "NO"]
    
    if not silent:
        print("\n" + "="*80)
        print(f"{'ALPHA DIFFERENTIAL FINGERPRINT (VECTORIZED)':^80}")
        print("="*80)
        print(f"Cohort Size | Winners: {len(winners)} | Losers: {len(losers)}\n")

    # Metrics
    if mode == "long":
        num_fields = [
            "Price as a % of 52 Wk H-L Range",
            "Relative Price Change (YTD)",
            "sales_growth",
            "operating_margin",
            "Theme_Score",
            "avg_volume",
            "RS_Rating",
            "long_score"
        ]
    else:
        num_fields = [
            "Price as a % of 52 Wk H-L Range",
            "Relative Price Change (YTD)",
            "sales_growth",
            "operating_margin",
            "Theme_Score",
            "avg_volume",
            "Short_RS_Rating",
            "Short_Score"
        ]
    
    if not silent:
        print("- DIFFERENTIAL AVERAGES (Winners vs Losers) -")
        print(f"{'Field':<35} | {'Winners Avg':<15} | {'Losers Avg':<15} | {'Edge'}")
        print("-" * 80)
        
    metrics_summary = []
    
    for f in num_fields:
        if f in winners.columns and f in losers.columns:
            w_col = pd.to_numeric(winners[f], errors="coerce")
            l_col = pd.to_numeric(losers[f], errors="coerce")
            
            w_avg = w_col.mean()
            l_avg = l_col.mean()
            
            if pd.notna(w_avg) and pd.notna(l_avg):
                diff = w_avg - l_avg
                edge_dir = ">>" if diff > 0 else "<<"
                if not silent:
                    print(f"{f:<35} | {w_avg:<15.2f} | {l_avg:<15.2f} | {diff:>5.2f} {edge_dir}")
                
                metrics_summary.append({
                    "Metric": f,
                    "Winners_Avg": w_avg,
                    "Losers_Avg": l_avg,
                    "Differential": diff
                })

    if not silent:
        print("\n- CATEGORICAL DENSITY CHECKS (Leading Cohort Indicators) -")
        
    cat_fields = ["Zacks Rank", "theme_class", "Bucket"]
    cat_summary = []
    
    for c in cat_fields:
        if c in winners.columns and c in losers.columns:
            if not silent: print(f"\n[{c.upper()}] Concentrated Distribution:")
            
            # Count density
            w_counts = winners[c].value_counts(normalize=True) * 100
            l_counts = losers[c].value_counts(normalize=True) * 100
            
            # Print top 3 densities for winners
            for val, pct in w_counts.head(3).items():
                val_str = str(val)
                if val_str.lower() != "nan" and val_str.lower() != "unknown":
                    l_pct = l_counts.get(val, 0.0)
                    if not silent:
                        print(f"  - {val_str}: {pct:.1f}% of Winners (vs {l_pct:.1f}% of Losers)")
                    cat_summary.append({
                        "Category": c,
                        "Value": val_str,
                        "Winner_Density_%": pct,
                        "Loser_Density_%": l_pct
                    })

    # Optional: We could save these to a CSV or return them
    return {
        "metrics": metrics_summary,
        "categories": cat_summary
    }

