import os
import sys
import pandas as pd
from pathlib import Path
from collections import Counter
import numpy as np

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
try:
    from backtesting.backtest_engine import run_backtest
except ImportError:
    print("Error: Could not import backtest_engine.")
    sys.exit(1)

def run_alpha_attribution():
    csv_dir = Path("c:/TABELA/market_data/input_files")
    
    print("\n========================================")
    print("PHASE 2: ALPHA ATTRIBUTION PROFILER")
    print("========================================")
    print("Collecting executed setups from baseline Backtest Engine...")
    
    # 1. Run the backtest silently to get the Trade Detail DataFrame
    bt_results = run_backtest(mode="long", silent=True)
    if not bt_results or "_detail_df" not in bt_results:
        print("No historical trades generated by current configuration.")
        return
        
    trades_df = bt_results["_detail_df"]
    if trades_df.empty:
        print("Trade list is empty.")
        return
        
    print(f"Captured {len(trades_df)} historical setups. Harvesting raw CSV components...\n")
    
    # Target numerical fields
    num_fields = [
        "Price as a % of 52 Wk H-L Range",
        "Relative Price Change (YTD)",
        "Sales Growth F(0)/F(-1)",
        "Operating Margin 12 Mo %",
        "Net Margin %"
    ]
    
    # Target categorical fields
    cat_fields = ["Zacks Rank", "Mapped_Theme", "Industry"]
    
    # 2. Extract Data
    enriched_trades = []
    
    # Pre-load CSVs into memory by date for fast lookup
    daily_csvs = {}
    for root, dirs, files in os.walk(csv_dir):
        for file in files:
            if file.endswith("stocks.csv"):
                d_str = file[:8]
                d_fmt = f"{d_str[:4]}-{d_str[4:6]}-{d_str[6:8]}"
                daily_csvs[d_fmt] = os.path.join(root, file)

    for idx, row in trades_df.iterrows():
        tdate = row["Entry Date"]
        ticker = row["Ticker"]
        is_win = (row["Win"] == "YES")
        
        trade_data = {"Ticker": ticker, "Win": is_win}
        
        if tdate in daily_csvs:
            try:
                df = pd.read_csv(daily_csvs[tdate])
                df["Ticker"] = df["Ticker"].str.strip()
                match = df[df["Ticker"] == ticker]
                
                if not match.empty:
                    m_row = match.iloc[0]
                    # Map numericals
                    for f in num_fields:
                        val = pd.to_numeric(m_row.get(f, np.nan), errors='coerce')
                        trade_data[f] = val
                    
                    # 52w Proximity Calculation
                    last_px = pd.to_numeric(m_row.get("Last Close", np.nan), errors='coerce')
                    high_52 = pd.to_numeric(m_row.get("52 Week High", np.nan), errors='coerce')
                    if pd.notna(last_px) and pd.notna(high_52) and high_52 > 0:
                        trade_data["Dist_to_52W_High"] = ((last_px - high_52) / high_52) * 100
                    else:
                        trade_data["Dist_to_52W_High"] = np.nan
                        
                    # Map categoricals
                    for c in cat_fields:
                        trade_data[c] = str(m_row.get(c, "Unknown"))
                        
            except Exception:
                pass
                
        enriched_trades.append(trade_data)
        
    analysis_df = pd.DataFrame(enriched_trades)
    
    winners = analysis_df[analysis_df["Win"] == True]
    losers = analysis_df[analysis_df["Win"] == False]
    
    print("--------------------------------------------------------------------------------")
    print(f"{'ALPHA DIFFERENTIAL FINGERPRINT':^80}")
    print("--------------------------------------------------------------------------------")
    print(f"Cohort Size | Winners: {len(winners)} | Losers: {len(losers)}\n")

    print("- NUMERICAL AVERAGES -")
    # Include calculated proximity
    report_num_fields = num_fields + ["Dist_to_52W_High"]
    
    print(f"{'Field':<35} | {'Winners Avg':<15} | {'Losers Avg':<15} | {'Edge'}")
    print("-" * 80)
    for f in report_num_fields:
        if f in winners.columns and f in losers.columns:
            w_avg = winners[f].mean()
            l_avg = losers[f].mean()
            if pd.notna(w_avg) and pd.notna(l_avg):
                diff = w_avg - l_avg
                edge_dir = ">>" if diff > 0 else "<<"
                print(f"{f:<35} | {w_avg:<15.2f} | {l_avg:<15.2f} | {diff:>5.2f} {edge_dir}")

    print("\n- CATEGORICAL DENSITY (Top 3 Densest Clusters) -")
    for c in cat_fields:
        if c in winners.columns and c in losers.columns:
            print(f"\n[{c.upper()}]")
            w_counts = winners[c].value_counts(normalize=True) * 100
            l_counts = losers[c].value_counts(normalize=True) * 100
            
            # Show top 3 for winners
            print(f"  Winners heavily clustered in:")
            for val, pct in w_counts.head(3).items():
                if val != "nan" and val != "Unknown":
                    # How does this compare to losers?
                    l_pct = l_counts.get(val, 0)
                    print(f"    - {val}: {pct:.1f}%  (Losers: {l_pct:.1f}%)")

if __name__ == "__main__":
    run_alpha_attribution()
