import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import io
from contextlib import redirect_stdout
from pathlib import Path

from pipeline.pipeline import run_tabela_pipeline
from config.runtime_context import context


if __name__ == "__main__":

    buffer = io.StringIO()

# Generated by Continue
    with redirect_stdout(buffer):
        run_tabela_pipeline()

    output = buffer.getvalue()

    # Save daily report
    report_dir = Path("market_data") / "daily_reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    report_file = report_dir / f"{context.market_date}.txt"
    report_file.write_text(output, encoding="utf-8")

    # Print to terminal
    try:
        print(output, end="")
    except UnicodeEncodeError:
        print(output.encode('ascii', 'replace').decode('ascii'), end="")